#!/bin/bash

me=`basename $0`

if [ "$me" == "twitter" ]; then
    docker run --rm -v "$PWD:/wd" python-utils twitter --oauth /wd/.twitter_oauth
else
    docker run --rm -v "$PWD:/wd" --workdir /wd python-utils python $@
fi
